function [language] = loadLanguageFrancais()
   language = {'Analyse spectrale des roulements',
        'La langue',
        'Sélectionnez un relèvement de la bibliothèque',
        'Série de roulement',
        'La fréquence de relèvement sélectionnée',
        'Fréquence de rotation (Hz)',
        'Fréquence orbitale (Hz)',
        'Les dimensions de palier sélectionnées',
        'Diamètre des éléments roulants (mm)',
        'PCD des éléments roulants (mm)',
        'Angle de contact (deg)',
        'Enregistrer le son',
        'Jouer le disque',
        'Analyse spectrale',
        'Comparaison',
        'Gain de fréquence',
        'Gain (dB)',
        'Fréquence de puissance',
        'Puissance (dB)',
        'la fréquence (Hz)',
        'Sortie',
        'Comparaison',
        'Gain (dB)',
        'la fréquence (Hz)',
        'le résultat de l''analyse:',
        'Nous pouvons voir que le roulement enregistré:',
        'celui de la bibliothèque.'
        'les fréquences',
        'à ceux du roulement',
        'de la bibliothèque, avec la plage d''erreur',
        'EST',
        'N''EST PAS',
        'SONT ÉGAUX',
        'NE SONT ÉGAUX PAS',
        'Analyser le son'};  
end