function [language] = loadLanguageRomana()
   language = {'Analiza spectrala a rulmentilor',
        'Limba',
        'Selecteaza rulmentul din biblioteca',
        'Serie rulment',
        'Frecventele rulmentului selectat',
        'Frecventa de rotatie (Hz)',
        'Frecventa de orbita (Hz)',
        'Dimensiunile rulmentului selectat',
        'Diametrul elementelor de rulare (mm)',
        'PCD elementelor de rulare (mm)',
        'Unghiul de contact (deg)',
        'Inregistreaza zgomot',
        'Reda inregistrarea',
        'Analiza spectrala',
        'Comparatie',
        'Amplitudine frecventa',
        'amplitudine',
        'Putere frecventa',
        'putere (W)',
        'frecventa (Hz)',
        'Iesire'};       
end