function [language] = loadLanguageFrancais()
   language = {'Analyse spectrale des roulements',
        'La langue',
        'Sélectionnez un relèvement de la bibliothèque',
        'Série de roulement',
        'La fréquence de relèvement sélectionnée',
        'Fréquence de rotation (Hz)',
        'Fréquence orbitale (Hz)',
        'Les dimensions de palier sélectionnées',
        'Diamètre des éléments roulants (mm)',
        'PCD des éléments roulants (mm)',
        'Angle de contact (deg)',
        'Enregistrer le son',
        'Jouer le disque',
        'Analyse spectrale',
        'Comparaison',
        'Gain de fréquence',
        'Gain',
        'Fréquence de puissance',
        'Puissance (W)',
        'la fréquence (Hz)',
        'Sortie'};  
end