function [language] = loadLanguageDeutsch()
      language = {'Spektrale Analyse von Lagern', 
        'Sprache',
        'W‰hle ein Lager aus der Bibliothek',
        'Lagerreihe',
        'Die ausgew‰hlte Lagerfrequenz',
        'Rotationsfrequenz (Hz)',
        'Orbitalfrequenz (Hz)',
        'Die ausgew‰hlten Lagermaﬂe',
        'Diameter of rolling elements (mm)',
        'Die ausgew‰hlten Lagermaﬂe (mm)',
        'Kontaktwinkel (deg)',
        'Ton aufnehmen',
        'Spiel den Rekord',
        'Spektral analyse',
        'Vergleich',
        'H‰ufigkeit gewinnen',
        'gewinnen',
        'Stromfrequenz',
        'Leistung (W)',
        'Frequenz (Hz)',
        'Ausgang'}; 
end