function [language] = loadLanguageDeutsch()
      language = {'Spektrale Analyse von Lagern', 
        'Sprache',
        'Wähle ein Lager aus der Bibliothek',
        'Lagerreihe',
        'Die ausgewählte Lagerfrequenz',
        'Rotationsfrequenz (Hz)',
        'Orbitalfrequenz (Hz)',
        'Die ausgewählten Lagermaße',
        'Diameter of rolling elements (mm)',
        'Die ausgewählten Lagermaße (mm)',
        'Kontaktwinkel (deg)',
        'Ton aufnehmen',
        'Spiel den Rekord',
        'Spektral analyse',
        'Vergleich',
        'Häufigkeit gewinnen',
        'gewinnen (dB)',
        'Stromfrequenz',
        'Leistung (dB)',
        'Frequenz (Hz)',
        'Ausgang',
        'Vergleich',
        'gewinnen (dB)',
        'Frequenz (Hz)',
        'das Analyseergebnis:',
        'Wir können das aufgezeichnete Lager sehen:',
        'der in der Bibliothek.'
        'die Frequenzen',
        'zu denen des Lagers',
        'aus der Bibliothek mit dem Fehlerintervall',
        'IST',
        'IST NICHT',
        'SIND GLEICH',
        'SIND GLEICH NICHT',
        'Sound analysieren'}; 
end