function [language] = loadLanguageEnglish()
       language = {'Spectral analyze of bearings',
        'Language',
        'Select a bearing from the library',
        'Bearing series',
        'The selected bearing frequency',
        'Rotation frequency (Hz)',
        'Orbital frequency (Hz)',
        'The selected bearing dimensions',
        'Diameter of rolling elements (mm)',
        'PCD of rolling elements (mm)',
        'Contact angle (deg)',
        'Record sound',
        'Play the record',
        'Spectral analysis',
        'Comparison',
        'Gain frequency',
        'gain (dB)',
        'Power frequency',
        'power (dB)',
        'frequency (Hz)',
        'Exit',
        'Comparison',
        'gain (dB)',
        'frequency (Hz)',
        'The analysis result:',
        'We can see that the recorded bearing:',
        'the one in the library.'
        'the frequencies',
        'to the ones of the bearing',
        'from the library, with the error interval',
        'IS',
        'IS NOT',
        'ARE EQUAL',
        'ARE NOT EQUAL',
        'Analyse sound'};  
end