function [language] = loadLanguageDeutsch()
      language = {'Spektrale Analyse von Lagern', 
        'Sprache',
        'Wähle ein Lager aus der Bibliothek',
        'Lagerreihe',
        'Die ausgewählte Lagerfrequenz',
        'Rotationsfrequenz (Hz)',
        'Orbitalfrequenz (Hz)',
        'Die ausgewählten Lagermaße',
        'Diameter of rolling elements (mm)',
        'Die ausgewählten Lagermaße (mm)',
        'Kontaktwinkel (deg)',
        'Ton aufnehmen',
        'Spiel den Rekord',
        'Spektral analyse',
        'Vergleich',
        'Häufigkeit gewinnen',
        'gewinnen (dB)',
        'Stromfrequenz',
        'Leistung (dB)',
        'Frequenz (Hz)',
        'Ausgang',
        'Vergleich',
        'gewinnen (dB)',
        'Frequenz (Hz)',
        'das Analyseergebnis:',
        'Wir können das aufgezeichnete Lager sehen:',
        'der in der Bibliothek.'
        'die Frequenzen',
        'zu denen des Lagers',
        'aus der Bibliothek mit dem Fehlerintervall',
        'IST',
        'IST NICHT',
        'SIND GLEICH',
        'SIND GLEICH NICHT',
        'Sound analysieren',
        'Hilfe',
        'Bedienungsanleitung',
        'Schließen',
        sprintf('Die Anwendung ermöglicht die Analyse der Aufzeichnung der Geräusche, die durch die Rotation bei einer bekannten Geschwindigkeit \neines Lagers erzeugt werden. Basierend auf der Geschwindigkeit berechnet die Anwendung die Rotationsfrequenzen und die Lagerbahn \ndes Lagers und vergleicht diese Frequenzen mit dem vom Lager erzeugten Geräuschspektrum. Wenn bei diesen Frequenzen Spitzen \nauftreten (mit einer Fehlermarge von der Standardabweichung), wird das Lager als das in der Bibliothek identifiziert. \n\n\n\nAnweisungen: \n\n1. Wähle ein Lager aus der Bibliothek. \n2. Die Frequenzen werden mit einer Standarddrehzahl von 1500 U / min berechnet. \n3. Drücken Sie die Schaltfläche "Noise Recording", um eine WAV-Datei aus dem Dateisystem zu laden. \n4. Die Amplituden-Frequenz- und Leistungs-Frequenz-Diagramme werden auf der Registerkarte Spektralanalyse angezeigt. \n5. Nachdem Sie auf die Schaltfläche "Vergleichen" geklickt haben, führt die Anwendung den Vergleichsalgorithmus aus, und auf der \nRegisterkarte "Vergleich" werden das Frequenzanalysediagramm und die in Schritt 2 berechneten Interessensintervalle angezeigt. \n6. Auf der rechten Seite des Diagramms werden basierend auf dieser Analyse einige Schlussfolgerungen angezeigt. \n\n\n\nHINWEIS: Die Graphen sind auf der OX-Achse bei 0-100 Hz begrenzt, da der interessierende Bereich (niedrige Frequenzen) vorhanden ist.'),
        'Stoppen der Aufnahme',
        'Pause'}; 
end