function [language] = loadLanguageRomana()
   language = {'Analiza spectrala a rulmentilor',
        'Limba',
        'Selecteaza rulmentul din biblioteca',
        'Serie rulment',
        'Frecventele rulmentului selectat',
        'Frecventa de rotatie (Hz)',
        'Frecventa de orbita (Hz)',
        'Dimensiunile rulmentului selectat',
        'Diametrul elementelor de rulare (mm)',
        'PCD elementelor de rulare (mm)',
        'Unghiul de contact (deg)',
        'Inregistreaza zgomot',
        'Reda inregistrarea',
        'Analiza spectrala',
        'Comparatie',
        'Amplitudine frecventa',
        'amplitudine (dB)',
        'Putere frecventa',
        'putere (dB)',
        'frecventa (Hz)',
        'Iesire',
        'Comparatie',
        'amplitudine (dB)',
        'fecventa (Hz)',
        'Rezultatul analizei:',
        'Putem observa ca rulmentul inregistrat:',
        'cel din biblioteca.'
        'frecventele',
        'cu cele ale rulmentului',
        'din biblioteca, cu intervalul de eroare',
        'ESTE',
        'NU ESTE',
        'SUNT EGALE',
        'NU SUNT EGALE',
        'Analizeaza zgomot'};       
end