function [language] = loadLanguageFrancais()
   language = {'Analyse spectrale des roulements',
        'La langue',
        'Sélectionnez un relèvement de la bibliothèque',
        'Série de roulement',
        'La fréquence de relèvement sélectionnée',
        'Fréquence de rotation (Hz)',
        'Fréquence orbitale (Hz)',
        'Les dimensions de palier sélectionnées',
        'Diamètre des éléments roulants (mm)',
        'PCD des éléments roulants (mm)',
        'Angle de contact (deg)',
        'Enregistrer le son',
        'Jouer le disque',
        'Analyse spectrale',
        'Comparaison',
        'Gain de fréquence',
        'Gain (dB)',
        'Fréquence de puissance',
        'Puissance (dB)',
        'la fréquence (Hz)',
        'Sortie',
        'Comparaison',
        'Gain (dB)',
        'la fréquence (Hz)',
        'le résultat de l''analyse:',
        'Nous pouvons voir que le roulement enregistré:',
        'celui de la bibliothèque.'
        'les fréquences',
        'à ceux du roulement',
        'de la bibliothèque, avec la plage d''erreur',
        'EST',
        'N''EST PAS',
        'SONT ÉGAUX',
        'NE SONT ÉGAUX PAS',
        'Analyser le son',
        'Aider',
        'Manuel d''instructions',
        'Fermer',
        sprintf('L''application permet d''analyser l''enregistrement du bruit produit par la rotation à une vitesse connue d''un roulement.\nEn fonction de la vitesse, l''application calcule les fréquences de rotation et l''orbite du palier et compare ces fréquences \navec le spectre de bruit produit par le palier. S''il y a des pics à ces fréquences (avec une marge d''erreur de l''écart-type), \nalors le relèvement est identifié comme celui de la bibliothèque.\n\n\n\nInstructions: \n\n1. Choisissez un relèvement de la bibliothèque. \n2. Les fréquences seront calculées à une vitesse standard de 1500 tr / min. \n3. Appuyez sur le bouton "Noise Recording" pour charger un fichier .wav à partir du système de fichiers. \n4. Les graphiques Amplitude-Fréquence et Puissance-Fréquence seront affichés dans l''onglet Analyse Spectrale. \n5. Après avoir cliqué sur le bouton "Comparer", l''application exécutera l''algorithme de comparaison, et dans l''onglet "Comparaison", \nle graphique d''analyse de fréquence et les fréquences d''intérêt calculées à l''étape 2 seront affichés. \n6. À la droite du graphique, certaines conclusions seront affichées en fonction de cette analyse. \n\n\n\nREMARQUE: Les graphes sont limités sur l''axe OX à 0-100 Hz car il y a la zone d''intérêt (basses fréquences).'),
        'Arrête d''enregistrer',
        'Pause'};  
end